### ISSUE TITLE
ExceptionInInitializerError 类加载时不会为实例变量赋值，对象创建时不会为静态变量赋值

### ISSUE THREAD

**Issue by MicroKibaco** [MicroKibaco/FestEC#1]
**Q:在MainDelegate testRestClient() 测试 get请求 抛出 ExceptionInInitializerError**
```java
FATAL EXCEPTION: main
                                                                   Process: com.asiainfo.festec, PID: 2461
                                                                   java.lang.ExceptionInInitializerError
                                                                       at com.asiainfo.latte.net.RestCreator$RetrofitHolder.access$200(RestCreator.java:36)
                                                                       at com.asiainfo.latte.net.RestCreator$RetrofitHolder$RestServiceHolder.<clinit>(RestCreator.java:67)
                                                                       at com.asiainfo.latte.net.RestCreator$RetrofitHolder$RestServiceHolder.access$000(RestCreator.java:64)
                                                                       at com.asiainfo.latte.net.RestCreator.getRestService(RestCreator.java:24)
                                                                       at com.asiainfo.latte.net.RestClient.request(RestClient.java:56)
                                                                       at com.asiainfo.latte.net.RestClient.get(RestClient.java:104)
                                                                       at com.asiainfo.festec.MainDelegate.testRestClient(MainDelegate.java:53)
                                                                       at com.asiainfo.festec.MainDelegate.onBindView(MainDelegate.java:27)
                                                                       at com.asiainfo.latte.delegates.BaseDelegate.onCreateView(BaseDelegate.java:46)
                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
                                                                       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
                                                                       at android.app.Activity.performStart(Activity.java:6992)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                    Caused by: java.lang.NullPointerException: baseUrl == null
                                                                       at retrofit2.Utils.checkNotNull(Utils.java:286)
                                                                       at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:451)
                                                                       at com.asiainfo.latte.net.RestCreator$RetrofitHolder.<clinit>(RestCreator.java:43)
                                                                       at com.asiainfo.latte.net.RestCreator$RetrofitHolder.access$200(RestCreator.java:36) 
                                                                       at com.asiainfo.latte.net.RestCreator$RetrofitHolder$RestServiceHolder.<clinit>(RestCreator.java:67) 
                                                                       at com.asiainfo.latte.net.RestCreator$RetrofitHolder$RestServiceHolder.access$000(RestCreator.java:64) 
                                                                       at com.asiainfo.latte.net.RestCreator.getRestService(RestCreator.java:24) 
                                                                       at com.asiainfo.latte.net.RestClient.request(RestClient.java:56) 
                                                                       at com.asiainfo.latte.net.RestClient.get(RestClient.java:104) 
                                                                       at com.asiainfo.festec.MainDelegate.testRestClient(MainDelegate.java:53) 
                                                                       at com.asiainfo.festec.MainDelegate.onBindView(MainDelegate.java:27) 
                                                                       at com.asiainfo.latte.delegates.BaseDelegate.onCreateView(BaseDelegate.java:46) 
                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080) 
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108) 
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290) 
                                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) 
                                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677) 
                                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604) 
                                                                       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333) 
                                                                       at android.app.Activity.performStart(Activity.java:6992) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                       at android.os.Looper.loop(Looper.java:164) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```
<img width="970" alt="screen shot 2018-03-03 at 22 20 47" src="https://user-images.githubusercontent.com/17723631/36935301-3bc0bff0-1f31-11e8-9bf1-e6fc8ae4e862.png">
<img width="954" alt="screen shot 2018-03-03 at 22 21 00" src="https://user-images.githubusercontent.com/17723631/36935303-4709f8d6-1f31-11e8-9202-77904f235910.png">

```java
    private void testRestClient() {

        RestClient.builder()
                .url("http://news.baidu.com")
                .success(new ISuccess() {
                    @Override
                    public void onSuccess(String response) {
                        Toast.makeText(getContext(), response, Toast.LENGTH_LONG).show();
                    }
                })
                .failure(new IFailure() {
                    @Override
                    public void onFailure() {

                    }
                })
                .error(new IError() {
                    @Override
                    public void onError(int code, String msg) {

                    }
                })
                .build()
                .get();

    }
```

**Comment by MicroKibaco** [comment]
**全局初始化Latte操作:**
ConfigType.API_HOST 没有初始化
```
Latte.init(this)
                .withApiHost("http://news.baidu.com/")
                .configure();
```
调用url为空.
